key trace size: 120000000
generate 120000000 keys exp distribution
generate duration 2.044963 s.
------------------------------------------------
Pmem:                  true
Key type:              unsigned long
Val type:              unsigned long
Keys:                  8 bytes each
Values:                8 bytes each
Entries:               120000000
Trace size:            120000000
Read:                  10000000 
Write:                 0 
Thread:                20 
Hash key flat:         true 
Hash val flat:         true 
Hash Buckets:          65536 
Hash Cell in Bucket:   16 
Hash Slot in Cell:     14 
Hash init capacity:    13631488 
Hash table size:       256 MB
Hash loadfactor:       0.72 
Cell Type:             CellMeta256V2 
Report interval:       0 s
Stats interval:        10000000 records
benchmarks:            load,ycsbd,ycsba,ycsbb,ycsbc,ycsbf
------------------------------------------------
[32mStart IPMWatcher for load
[0mload         :       0.092 micros/op 10.349902 Mops/s;
DIMM0 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       5733.08 |        5890.72 |    11491.91 |      8652.67 |   2.00 |   1.47 |
DIMM1 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       5736.45 |        5889.79 |    11526.30 |      8662.33 |   2.01 |   1.47 |
DIMM2 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       5758.43 |        5902.46 |    11530.25 |      8684.48 |   2.00 |   1.47 |
DIMM3 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       5711.19 |        5889.29 |    11454.41 |      8584.83 |   2.01 |   1.46 |
DIMM4 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       5707.28 |        5889.15 |    11432.20 |      8581.30 |   2.00 |   1.46 |
DIMM5 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       5709.33 |        5889.42 |    11438.17 |      8586.65 |   2.00 |   1.46 |
*SUM* | DIMM-R:  5864.5 MB/s. User-R:  2925.4 MB/s   | DIMM-W:  4406.7 MB/s, User-W:  3010.1 MB/s. Time:  11.74s
[32mDestroy IPMWatcher.
[0m
[32mStart IPMWatcher for ycsbd
[0mthread  3, between 22800000 - 24000000
thread  9, between 58800000 - 60000000
thread 10, between 64800000 - 66000000
thread 15, between 94800000 - 96000000
thread  6, between 40800000 - 42000000
thread  2, between 16800000 - 18000000
thread  8, between 52800000 - 54000000
thread  0, between 4800000 - 6000000
thread 11, between 70800000 - 72000000
thread  4, between 28800000 - 30000000
thread 16, between 100800000 - 102000000
thread  5, between 34800000 - 36000000
thread 17, between 106800000 - 108000000
thread 19, between 118800000 - 120000000
thread  7, between 46800000 - 48000000
thread 14, between 88800000 - 90000000
thread 12, between 76800000 - 78000000
thread 18, between 112800000 - 114000000
thread 13, between 82800000 - 84000000
thread  1, between 10800000 - 12000000
ycsbd        :       0.012 micros/op 82.267084 Mops/s; (insert: 0, read: 1200000)
DIMM0 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |        546.39 |           0.02 |     1071.99 |         0.76 |   1.96 |  38.03 |
DIMM1 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |        544.70 |           0.02 |     1068.34 |         0.81 |   1.96 |  38.16 |
DIMM2 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |        545.90 |           0.02 |     1070.79 |         0.77 |   1.96 |  37.93 |
DIMM3 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |        544.68 |           0.02 |     1071.74 |         0.76 |   1.97 |  37.24 |
DIMM4 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |        544.89 |           0.02 |     1072.48 |         0.77 |   1.97 |  39.82 |
DIMM5 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |        543.93 |           0.02 |     1070.01 |         0.77 |   1.97 |  38.96 |
*SUM* | DIMM-R:  6686.1 MB/s. User-R:  3403.2 MB/s   | DIMM-W:     4.8 MB/s, User-W:     0.1 MB/s. Time:   0.96s
[32mDestroy IPMWatcher.
[0m
[32mStart IPMWatcher for ycsba
[0mycsba        :       0.034 micros/op 27.790237 Mops/s; (insert: 3001727, read: 2998273)
DIMM0 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2738.14 |        1220.89 |     5118.72 |      2473.40 |   1.87 |   2.03 |
DIMM1 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2735.05 |        1219.99 |     5128.06 |      2477.11 |   1.87 |   2.03 |
DIMM2 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2737.32 |        1220.70 |     5118.22 |      2474.18 |   1.87 |   2.03 |
DIMM3 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2736.95 |        1220.56 |     5118.36 |      2473.44 |   1.87 |   2.03 |
DIMM4 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2739.58 |        1221.62 |     5124.18 |      2478.08 |   1.87 |   2.03 |
DIMM5 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2736.43 |        1220.34 |     5117.29 |      2473.71 |   1.87 |   2.03 |
*SUM* | DIMM-R:  6397.0 MB/s. User-R:  3419.4 MB/s   | DIMM-W:  3091.8 MB/s, User-W:  1524.9 MB/s. Time:   4.80s
[32mDestroy IPMWatcher.
[0m
[32mStart IPMWatcher for ycsbb
[0mycsbb        :       0.013 micros/op 71.038736 Mops/s; (insert: 298405, read: 5701595)
DIMM0 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2423.08 |         121.70 |     5102.03 |       247.81 |   2.11 |   2.04 |
DIMM1 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2420.27 |         121.70 |     5098.67 |       248.48 |   2.11 |   2.04 |
DIMM2 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2422.06 |         121.51 |     5100.95 |       247.67 |   2.11 |   2.04 |
DIMM3 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2422.59 |         121.60 |     5099.92 |       247.84 |   2.11 |   2.04 |
DIMM4 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2424.92 |         121.61 |     5104.41 |       247.85 |   2.10 |   2.04 |
DIMM5 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2421.81 |         121.57 |     5098.44 |       247.79 |   2.11 |   2.04 |
*SUM* | DIMM-R: 13306.3 MB/s. User-R:  6319.4 MB/s   | DIMM-W:   646.7 MB/s, User-W:   317.3 MB/s. Time:   2.30s
[32mDestroy IPMWatcher.
[0m
[32mStart IPMWatcher for ycsbc
[0mycsbc        :       0.009 micros/op 108.513066 Mops/s; (insert: 0, read: 6000000)
DIMM0 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2416.03 |           0.01 |     5114.94 |         2.36 |   2.12 | 159.45 |
DIMM1 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2413.04 |           0.01 |     5110.21 |         2.49 |   2.12 | 168.63 |
DIMM2 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2415.28 |           0.01 |     5113.69 |         2.38 |   2.12 | 161.45 |
DIMM3 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2415.45 |           0.01 |     5112.74 |         2.42 |   2.12 | 163.79 |
DIMM4 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2417.99 |           0.01 |     5116.97 |         2.42 |   2.12 | 163.98 |
DIMM5 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2414.62 |           0.01 |     5111.33 |         2.37 |   2.12 | 160.43 |
*SUM* | DIMM-R: 17601.8 MB/s. User-R:  8314.6 MB/s   | DIMM-W:     8.3 MB/s, User-W:     0.1 MB/s. Time:   1.74s
[32mDestroy IPMWatcher.
[0m
[32mStart IPMWatcher for ycsbf
[0mycsbf        :       0.028 micros/op 33.722005 Mops/s; (read_modify: 3000894, read: 2999106)
DIMM0 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2783.24 |        1220.98 |     5137.58 |      2478.18 |   1.85 |   2.03 |
DIMM1 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2780.34 |        1220.41 |     5147.88 |      2483.25 |   1.85 |   2.03 |
DIMM2 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2782.74 |        1220.82 |     5138.22 |      2479.35 |   1.85 |   2.03 |
DIMM3 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2782.16 |        1220.43 |     5138.42 |      2479.09 |   1.85 |   2.03 |
DIMM4 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2784.85 |        1221.37 |     5142.98 |      2481.95 |   1.85 |   2.03 |
DIMM5 | Read from IMC | Write from IMC |  Read DIMM  |  Write DIMM  |   RA   |   WA   |
  MB  |       2781.86 |        1220.68 |     5136.44 |      2479.05 |   1.85 |   2.03 |
*SUM* | DIMM-R:  7561.0 MB/s. User-R:  4093.0 MB/s   | DIMM-W:  3648.2 MB/s, User-W:  1795.7 MB/s. Time:   4.08s
[32mDestroy IPMWatcher.
[0m
